server:
  port: 5555

logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      de.cdelmonte: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

zuul:
  prefix:  /api
  sensitiveHeaders: Cookie,Set-Cookie 
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

spring.sleuth.sampler.probability: 1

security:
  oauth2:
    resource:
      id: oauth2_id
      userInfoUri: http://localhost:8901/auth/user

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: routes,filters

spring:
  sleuth:
    zuul:
      enabled: true
      
hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
# Increase the Hystrix timeout to 60s (per service)
# hystrix.command.<serviceName>.execution.isolation.thread.timeoutInMilliseconds: 60000
